name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          pavanidilip/comfyui-runpod:cuda
          pavanidilip/comfyui-runpod:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Success message
      run: |
        echo "✅ Docker image built successfully!"
        echo "Image: pavanidilip/comfyui-runpod:cuda"
        echo "Also tagged as: pavanidilip/comfyui-runpod:latest"
